name: 'Critical Journey'
description: 'A GitHub Action to run a Critical Journey UI test'
author: 'foreai-co'

inputs:
  test_id:
    description: 'ID of the test to be run.'
    required: false
    default: ''
  
  test_suite_id:
    description: 'ID of the test suite to be run.'
    required: false
    default: ''
  
  service_account_key:
    description: 'Key to the service account that will run the test.'
    required: true
    default: ''

outputs:
  result:
    description: 'A message that includes information about the status of the run.'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'cloud-lightning'
  color: 'blue'
